import type { OptionsGroup } from '../OptionsList.types';
import type { SncComponent } from '@/Types/SncComponent';

export type OptionsGroupProps = SncComponent<
  OptionsGroup & {
    /**
     * Toggle rendering of checkboxes.
     * @default true
     */
    checkbox?: boolean;
    /**
     * Whether this group's children are expanded when the list first renders.
     * @default false
     */
    defaultNestedExpanded?: boolean;
    /**
     * Number of layers by which to indent the content.
     * @default 0
     */
    indent?: number;
    /**
     * Fires with the full updated array of selected ids whenever this group's selection changes.
     */
    onSelectionChange?: (selected: string[]) => void;
    /**
     * Allow selection of all child options with a single click. Ported verbatim from the legacy
     * library, including its quirk of hiding the collapse chevron and disabling manual
     * expand/collapse entirely while this is `true`.
     * @default false
     */
    selectAll?: boolean;
    /**
     * Array of currently selected option ids, scoped to this group's descendants.
     */
    selectedOptions?: string[];
    /**
     * Additive — not part of the ported legacy shape. Threaded through to this group's nested
     * `OptionsList` for `CmdK`'s keyboard-highlight state.
     */
    activeId?: string | null;
  }
>;

export type OptionsGroupButtonProps = OptionsGroupProps & {
  /**
   * Whether every one of this group's child options is currently selected.
   */
  allSelected: boolean;
  /**
   * Toggles selection of every child option at once.
   */
  onToggleSelectAll: () => void;
  /**
   * Fires with the full updated array of selected ids.
   */
  onOptionsChange?: (selected: string[]) => void;
  /**
   * Toggles whether this group's children are visible.
   */
  onToggleChildVisibility?: () => void;
  /**
   * Ids of this group's currently selected child options.
   */
  selectedOptionIds: string[];
  /**
   * Whether this group's children are currently visible.
   */
  isChildItemsVisible: boolean;
  /**
   * Id of the header button, generated by the parent `OptionsGroup` — links the content panel back
   * to it via `aria-labelledby`, matching `Accordion`'s own header/panel id pairing.
   */
  headerId: string;
  /**
   * Id of the content panel, generated by the parent `OptionsGroup` — referenced by the header
   * button's `aria-controls`, matching `Accordion`'s own header/panel id pairing.
   */
  panelId: string;
};
